version: "0.1"
user: sushobhitd
key: glcUH6FSqT4uawyIL1RbXJr4ePasM1NuTZTkvxlQEz2IkSHLQt
testSuites: []
pre: [npm install]
runson: win
autosplit: true
concurrency: 1
testDiscovery:
  autosubset: true
  command: grep -lr 'describe' tests/specs/*.js
  mode: dynamic
  type: raw
testRunnerCommand: npx wdio conf\wdio.conf.js --spec tests\specs\demo.js
globalTimeout: 90
testSuiteTimeout: 90
testSuiteStep: 90
cacheDirectories:
- .node_modules
cacheKey: '{{ checksum "package-lock.json" }}'
jobID: 7bc66fa9-f6f2-4d10-b916-5e6534e00b12
codeDirectory: WebdriverIO-HyperExecute-Sample
